<a href="https://colab.research.google.com/github/Shamil2007/Python-Tutorials/blob/main/Python_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variables

Create a variable with name "x" and a value of 10. Execute.

In [1]:
x = 10

Tell the computer to show you the value of that variable.

In [2]:
x

10

Can you think of a second way to obtain the same result?

In [3]:
print(x)

10


On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [4]:
a, b, c, d = 10, 20, 30, 40

Tell the computer to show you the value corresponding to the variable "b".

In [5]:
b

20

Do the same for "d".

In [6]:
d

40

_________________________________

# Numbers and Boolean Values

Create a variable equal to "True".

In [7]:
isTrue = True

Check its type.

In [8]:
type(isTrue)

bool

Create a variable equal to 99.

In [9]:
var = 98

Check its type.

In [10]:
type(98)

int

Check the type of the value 0.99.

In [11]:
type(0.99)

float

Turn 99 into a float.

In [12]:
float(99)

99.0

Turn 0.99 into an integer. What value did you get?

In [13]:
int(0.99)

0

_________________________________

# Strings

Assign the value of 100 to the variable "m".

In [14]:
m = 100

With the help of the variable "m", write one line of code where the output after executuion would be 100 days.

Hint: You could provide four answers to this question!

In [15]:
print(str(m) + " " + "days")

100 days


In [16]:
print(m, "days")

100 days


In [17]:
print(f"{m} days")

100 days


Produce an output equal to It's cool, isn't it?

In [18]:
checkCool = "It's cool, isn't it?"

Fix the string below.

In [19]:
"Don't be shy"

"Don't be shy"

Produce an output equal to Click "OK".

In [20]:
print('Click "OK"')

Click "OK"


Include a plus sign in your line of code to produce 'Big Houses'.

In [21]:
print("'Big" + " Houses'")

'Big Houses'


Include a trailing comma in your line of code to produce Big Houses.

In [22]:
print("Big", "Houses")

Big Houses


__________________

# Arithmetic operators

Combine 15 and 23.

In [23]:
15 + 23

38

Subtract 50 from 26.

In [24]:
50 - 26

24

Divide 20 by 4.

In [25]:
20 / 4

5.0

Divide 22 by 4.

In [26]:
22 / 4

5.5

Obtain the remainder of the division of 22 by 4.

In [27]:
22 % 4

2

Divide the float 22 by 4.

In [28]:
22. / 4

5.5

In [29]:
22. // 4

5.0

Multiply 6 by 8.

In [30]:
6 * 8

48

Raise 15 to the power of 2.

In [31]:
15 ** 2

225

_____________________

# The double-equality sign

Demonstrate that 100 is not equal to 98.

In [32]:
100 != 98

True

__________________________

# Reassign Values

Assign the value of 14 to a variable p.

In [33]:
a = 14
p = a
p

14

Calculate p + 10.

In [34]:
p = p + 10
p

24

Now, assign 30 to the variable p.

In [35]:
p = 30
p

30

Calculate p + 10.

In [36]:
p = p + 10
p

40

Observe how the value of p is always the last one you have assigned.

In [37]:
p = 5
print(p)

p = 10
print(p)

5
10


___________________

# Indexing Elements

Extract the letter 'B' from "Bingo!".

In [38]:
word = "Bingo!"

In [39]:
word[0]

'B'

Extract the letter "u" from "Constitution".

In [40]:
word = "Constitution"

In [41]:
word[7]

'u'

________________

# Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [42]:
def ten(x):
    x = 10
    return x

print(ten(3))

10


___________________

# Comparison Operators

Verify that 25 is smaller than 30.

In [43]:
25 < 30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3.

In [44]:
5 * 3 <= 5 ** 3

True

Verify that 100 is equal to 10 square.

In [45]:
100 == 10 ** 2

True

Verify that 53 is not equal to 46.

In [46]:
53 != 46

True

___________________

# Logical and Identity Operators

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Check whether the following code is True or False.

False or not True and not False

In [47]:
print(5 == 6 or 7 > 8 and 12 < 16)

False


True and not False and True or not False

In [48]:
a = 10
b = 5
c = 7

print(a > b and not (b > a) and c == 7 or not (a < b))

True


True or False and False

In [49]:
x = 3
y = 4
z = 5

print(x < y or y > z and z != 5)

True


False and True or False

In [50]:
m = 8
n = 10

print(m > n and n < m or n == 8)

False


Using an identity operator, verify that 10 is not the same as 12.

In [51]:
print(10 is not 12)

True


<>:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
/tmp/ipython-input-1994554126.py:1: SyntaxWarning: "is not" with 'int' literal. Did you mean "!="?
  print(10 is not 12)


Using an identity operator, verify that 50 is the same as 50.

In [52]:
print(50 is 50)

True


<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-2810800453.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  print(50 is 50)


____________________

# Introduction to the IF statement

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [53]:
if 5 > 2:
    print("The condition has been satisfied")

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 and y is less than or equal to 13. Change the values assigned to x and y and re-run the cell to verify your code still works.

In [54]:
x = 10
y = 25

if x > 3 and y > 13:
    print("Both conditions are correct")

if x <= 3 and y <= 13:
    print("At least one of the conditions is false")

Both conditions are correct


In [55]:
x = 2
y = 10

if x > 3 and y > 13:
    print("Both conditions are correct")

if x <= 3 and y <= 13:
    print("At least one of the conditions is false")

At least one of the conditions is false


____________________________

# Add an ELSE Statement

Let x represent the number of orders received during a certain day. Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [56]:
x = 102

if x > 100:
    print("A busy day")
else:
    print("A calm day")

A busy day


In [57]:
x = 97

if x > 100:
    print("A busy day")
else:
    print("A calm day")

A calm day


_________________

# Else if, for Brief - ELIF

Assign 200 to x. Create the following piece of code: If x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average"; and If x <= 100, print out "Small". Use the If, Elif, and Else keywords in your code.

In [58]:
x = 200

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
else:
    print("Small")

Average


Change the initial value of x to see how your output will vary.

In [59]:
x = 50

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
else:
    print("Small")

Small


Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. Let x carry the value of 50 and then of -50 to check if your code is correct.

In [60]:
x = 50

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
elif x >= 0 and x <= 100:
    print("Small")
else:
    print("Negative")

Small


In [61]:
x = -50

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
elif x >= 0 and x <= 100:
    print("Small")
else:
    print("Negative")

Negative


_____________________

# Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [62]:
def multiply_by_two(x):
    return x * 2

In [63]:
multiply_by_two(8)

16

Define a funciton that returns a float value equal to its argument divided by 2.

In [64]:
def divide_by_two(x):
    return x / 2

In [65]:
divide_by_two(4)

2.0

_________________

# Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. Call the function with some argument to verify it works properly.

Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!

In [66]:
def power_of_two(x):
    result = x ** 2
    print(x, "Raised to the power of 2:", result)
    return result

In [67]:
power_of_two(5)

5 Raised to the power of 2: 25


25

_____________

# Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3. Verify your code was correct by calling the second function with an argument of 5. Was your output equal to 30?

In [68]:
def add_five(x):
    return x + 5

def multiply_by_three(x):
    new_value = add_five(x)
    return new_value * 3

In [69]:
result = multiply_by_three(5)

print(f"Answer when value is 5: {result}")
print(f"Is equal to 30? {result == 30}")

Answer when value is 5: 30
Is equal to 30? True


____________________

# Combining Conditional Statements and Functions

Define a function, called compare_the_two(), with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [70]:
def compare_the_two(a, b):
    if a > b:
        print("Greater")
    elif a < b:
        print("Less")
    else:
        print("Equal")

In [71]:
compare_the_two(8, 6)
compare_the_two(40, 46)
compare_the_two(12, 12)

Greater
Less
Equal


__________________

# Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [72]:
max(25, 65, 890, 15)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [73]:
min(25, 65, 890, 15)

15

Find the absolute value of -100

In [74]:
abs(-100)

100

Round the value of 55.5. Did you obtain 56.0?

In [75]:
round(55.5)

56

In [76]:
round(55.5, 0)

56.0

Round 35.56789 to the third digit.

In [77]:
round(35.56789, 3)

35.568

Find the sum of all elements in the provided list, called "Numbers".

In [78]:
Numbers = [1, 5, 64, 24.5]

In [79]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [80]:
pow(10, 3)

1000

How many characters are there in the word "Elephant"?

In [81]:
word = "Elephant"
len(word)

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number. Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [82]:
def distance_from_zero(x):
    if isinstance(x, float) or isinstance(x, int):
        return abs(x)
    else:
        print("Not Possible")
        return None

In [83]:
print(distance_from_zero(-10))

10


In [84]:
print(distance_from_zero("cat"))

Not Possible
None


____________________

# Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [85]:
Numbers = [10, 25, 40, 50]

Print the second element from the list.

In [86]:
Numbers[1]

25

Print the 0th element.

In [87]:
Numbers[0]

10

Print the third-to-last element using a minus sign in the brackets.

In [88]:
Numbers[-3]

25

Substitute the number 10 with the number 15.

In [89]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [90]:
del Numbers[1]
Numbers

[15, 40, 50]

In [91]:
# Numbers.remove(25)
# Numbers

______________

# Help Yourself with Methods

Append the number 100 to the Numbers list.

In [92]:
Numbers = [15, 40, 50]

In [93]:
Numbers.append(100)
Numbers

[15, 40, 50, 100]

With the help of the "extend method", add the numbers 115 an 140 to the list.

In [94]:
Numbers.extend([115, 140])
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [95]:
print(f"The fourth element of the Numbers list is: {Numbers[3]}")

The fourth element of the Numbers list is: 100


How many elements are there in the Numbers list?

In [96]:
len(Numbers)

6

________________

# List Slicing

In [97]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [98]:
Numbers[3:5]

[100, 115]

Using slicing, extract the first four elements from the list.

In [99]:
Numbers[:4]

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [100]:
Numbers[2:]

[50, 100, 115, 140]

Using slicing, extract the last 4 elements from the list.

In [101]:
Numbers[len(Numbers) - 4:]

[50, 100, 115, 140]

Which is the position of the value 15?

In [102]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists.

In [103]:
Two_Numbers = [1, 2]

All_Numbers = Numbers + Two_Numbers
All_Numbers

[15, 40, 50, 100, 115, 140, 1, 2]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [104]:
Numbers.sort(reverse=True)
Numbers

[140, 115, 100, 50, 40, 15]

__________________

# Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford".

In [105]:
Cars = ("BMW", "Dodge", "Ford")

Access the second element of this tuple.

In [106]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [107]:
name, age = 'Peter,24'.split(',')

In [108]:
name

'Peter'

In [109]:
age

'24'

Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle. Call the function with arguments 2 and 10 to verify it worked correctly.

In [110]:
def rectangle_properties(length, width):
    area = length * width
    perimeter = 2 * (length + width)
    return area, perimeter

In [111]:
area, perimeter = rectangle_properties(2, 10)
print("Area:", area)
print("Perimeter:", perimeter)

Area: 20
Perimeter: 24


________________________

# Dictionaries

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

This is the menu of a close-by restaurant:

In [112]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [113]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [114]:
Menu["mean_5"] = "Soup"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'mean_5': 'Soup'}

Replace the Hamburger with a Cheeseburger.

In [115]:
Menu["meal_3"] = "Cheeseburger"
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'mean_5': 'Soup'}

Attach the Desserts list in the form of a sixth meal.

In [116]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [117]:
Menu["meal_6"] = Dessert
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'mean_5': 'Soup',
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars): 10, 5, 8, 12, 5. Start by Price_list = {}.

In [118]:
Price_list = {}

Price_list = {
    'meal_1': 10,
    'meal_2': 5,
    'meal_3': 8,
    'meal_4': 12,
    'meal_5': 5
}

Price_list

{'meal_1': 10, 'meal_2': 5, 'meal_3': 8, 'meal_4': 12, 'meal_5': 5}

Use the .get() method to check the price of the Spaghetti.

In [119]:
Price_list.get('meal_1')

10

_____________________

# For Loops

Create a For loop that prints every digit on a new line.

In [120]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [121]:
for i in digits:
    print(i)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [122]:
for i in digits:
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

________________

# While Loops and Incrementing

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a while loop that will print all odd numbers from 0 to 30 on the same row.

Hint: There are two ways in which you can create the odd values!

In [123]:
i = 0
while i < 30:
    if i % 2 == 1:
        print(i)
    i += 1

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


____________

# Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [124]:
numbers = []
for i in range(1, 10):
    numbers.append(i)
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Use the range() function to create a list with all numbers from 0 to 19.

In [125]:
numbers = []
for i in range(19):
    numbers.append(i)
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

Use the range function to create a list with all even numbers from 0 to 30 included.

In [126]:
numbers = []
for i in range(30):
    if i % 2 == 0:
        numbers.append(i)
numbers

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

_______________________

# Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [127]:
numbers = []
for i in range(1, 10):
    numbers.append(i)

for num in numbers:
    print(num * 2)

2
4
6
8
10
12
14
16
18


Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even". Help yourself with the range() function to solve this exercise.

In [128]:
for num in range(1, 31):
    if num % 2 == 0:
        print("Even")
    else:
        print(num)

1
Even
3
Even
5
Even
7
Even
9
Even
11
Even
13
Even
15
Even
17
Even
19
Even
21
Even
23
Even
25
Even
27
Even
29
Even


You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10. Find two solutions of this problem.

In [129]:
n = [1,2,3,4,5,6]

In [130]:
for num in n:
    print(num * 10)

10
20
30
40
50
60


In [131]:
print([num * 10 for num in n])

[10, 20, 30, 40, 50, 60]


_________________

# All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. You might prefer using the x[item] structure for indicating the value of an element from the list.

In [132]:
nums = [1,12,24,31,51,70,100]

In [133]:
count = 0
i = 0

while i < len(nums):
    if nums[i] < 20:
        count += 1
    i += 1

count

2

____________

# Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [134]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [135]:
for item in prices:
    if prices[item] >= 5:
        money_spent += prices[item] * quantity[item]

money_spent

50

And how much did Jan spent on products that cost less than 5 dollars?

In [136]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [137]:
for item in prices:
    if prices[item] < 5:
        money_spent += prices[item] * quantity[item]
money_spent

24